[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    links2004/WebSockets@^2.6.1
    bblanchon/ArduinoJson@^7.3.0
    olikraus/U8g2@^2.36.12
build_flags =
    -DCORE_DEBUG_LEVEL=3
